//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marvin.ClientFramework.Kernel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marvin.ClientFramework.Kernel.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly configuration loaded ({0}) ....
        /// </summary>
        public static string Loader_AssemblyConfigurationLoaded {
            get {
                return ResourceManager.GetString("Loader_AssemblyConfigurationLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was loaded ....
        /// </summary>
        public static string Loader_AssemblyLoaded {
            get {
                return ResourceManager.GetString("Loader_AssemblyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component initializer found {0} types. Starting to initialize..
        /// </summary>
        public static string Loader_ComponentInitializingStarting {
            get {
                return ResourceManager.GetString("Loader_ComponentInitializingStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is based on the MaRVIN Platform! - Corporate Technology &amp; Value Chain.
        /// </summary>
        public static string Loader_Credits {
            get {
                return ResourceManager.GetString("Loader_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing {0} ....
        /// </summary>
        public static string Loader_InitializingComponent {
            get {
                return ResourceManager.GetString("Loader_InitializingComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing {0}.
        /// </summary>
        public static string Loader_InitializingModule {
            get {
                return ResourceManager.GetString("Loader_InitializingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing {0} done ....
        /// </summary>
        public static string Loader_InitializingModuleDone {
            get {
                return ResourceManager.GetString("Loader_InitializingModuleDone", resourceCulture);
            }
        }
    }
}
