//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moryx.Tools.WcfClient.UI.Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moryx.Tools.WcfClient.UI.Viewer.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF Connections.
        /// </summary>
        public static string ModuleController_Title {
            get {
                return ResourceManager.GetString("ModuleController_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Version.
        /// </summary>
        public static string WcfClientViewerWorkspaceView_ClientVersion {
            get {
                return ResourceManager.GetString("WcfClientViewerWorkspaceView_ClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Client Version.
        /// </summary>
        public static string WcfClientViewerWorkspaceView_MinClientVersion {
            get {
                return ResourceManager.GetString("WcfClientViewerWorkspaceView_MinClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Server Version.
        /// </summary>
        public static string WcfClientViewerWorkspaceView_MinServerVersion {
            get {
                return ResourceManager.GetString("WcfClientViewerWorkspaceView_MinServerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Version.
        /// </summary>
        public static string WcfClientViewerWorkspaceView_ServerVersion {
            get {
                return ResourceManager.GetString("WcfClientViewerWorkspaceView_ServerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string WcfClientViewerWorkspaceView_Service {
            get {
                return ResourceManager.GetString("WcfClientViewerWorkspaceView_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string WcfClientViewerWorkspaceView_State {
            get {
                return ResourceManager.GetString("WcfClientViewerWorkspaceView_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF Connections.
        /// </summary>
        public static string WcfClientViewerWorkspaceView_Title {
            get {
                return ResourceManager.GetString("WcfClientViewerWorkspaceView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ties.
        /// </summary>
        public static string WcfClientViewerWorkspaceView_Tries {
            get {
                return ResourceManager.GetString("WcfClientViewerWorkspaceView_Tries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri.
        /// </summary>
        public static string WcfClientViewerWorkspaceView_Uri {
            get {
                return ResourceManager.GetString("WcfClientViewerWorkspaceView_Uri", resourceCulture);
            }
        }
    }
}
